# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09eb02ae96de69fcad703054c8070c7e3321553bd8851aedbc7033bcd24fc461162b3029a85b98ed34dfb47124b6a003445cd837dce4f70a641c6f7b857a3831

test:
  secret_key_base: 8a428a8136a8410c29f2769c8d8215999b52e1a6b6ef17a2afa8ae3bb8924d23fb501b8c98c0fbed3c55c48f7141b619f8624fde7967e567532f5464a4783484

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
